# Generated by Django 5.1.3 on 2024-11-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='user',
            new_name='owner',
        ),
    ]
