# Generated by Django 5.1.3 on 2024-11-19 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_payments_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
