name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Шаг 3: Обновление pip
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    # Шаг 4: Установка зависимостей
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # Шаг 5: Запуск тестов
    - name: Run tests
      run: |
        python manage.py test

    # Шаг 6: Деплой на сервер
    - name: Deploy to Server
      if: success()  # Выполнять деплой только при успешных тестах
      run: |
        ssh -o StrictHostKeyChecking=no root@185.237.165.164 << 'EOF'
        cd /root/myproject
        git pull origin main
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        systemctl restart gunicorn
        EOF

    # Шаг 7: Уведомление об успешном деплое
    - name: Notify success
      if: success()
      run: echo "Deployment successful!"
