name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускается при каждом пуше в ветку main
  pull_request:
    branches:
      - main  # Запускается при создании pull request в main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Укажите используемую версию Python

    # Шаг 3: Обновление pip
    - name: Upgrade pip
      run: pip install --upgrade pip

    # Шаг 4: Установка зависимостей
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Шаг 5: Запуск тестов
    - name: Run tests
      run: |
        python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: your_project.settings  # Укажите настройки Django

    # Шаг 6: Деплой на сервер (после успешного выполнения тестов)
    - name: Deploy to server
      if: success()  # Выполняется только если предыдущие шаги успешны
      run: |
        ssh -o StrictHostKeyChecking=no root@<YOUR_SERVER_IP> << 'EOF'
          cd /path/to/your/project
          source venv/bin/activate
          git pull origin main
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          systemctl restart gunicorn
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
