# Generated by Django 5.1.3 on 2024-11-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0002_alter_course_preview_alter_lesson_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_to_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
