name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          sudo service postgresql start
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '12345';"
          sudo -u postgres psql -c "CREATE DATABASE lesson;"
          sudo -u postgres psql -c "CREATE ROLE runner WITH LOGIN PASSWORD '12345';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE lesson TO runner;"
          sudo -u postgres psql -c "GRANT CREATE ON SCHEMA public TO runner;"

      - name: Run makemigrations
        working-directory: /home/runner/work/Docker-Compose/Docker-Compose
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          DATABASE_URL: postgres://runner:12345@localhost:5432/lesson
        run: |
          poetry run python manage.py makemigrations

      - name: Run migrate
        working-directory: /home/runner/work/Docker-Compose/Docker-Compose
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          DATABASE_URL: postgres://runner:12345@localhost:5432/lesson
        run: |
          poetry run python manage.py migrate

      - name: Run tests
        working-directory: /home/runner/work/Docker-Compose/Docker-Compose
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          DATABASE_URL: postgres://runner:12345@localhost:5432/lesson
        run: |
          poetry run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
        run: |
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" ssh -v -o StrictHostKeyChecking=no root@185.237.165.164 "cd /var/www/homework_35_2 && git pull && poetry install && sudo systemctl restart nginx"
